---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/dhcp-server"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/dhcp-client"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/sztp-server"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/sztp-agent"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/sztp-simulator"
    schedule:
      interval: "weekly"