# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2022-2023 Dell Inc, or its subsidiaries.
---
version: '3.7'

services:
  nmap:
    image: docker.io/instrumentisto/nmap:7.94
    networks:
      - opi
    command: --script broadcast-dhcp-discover

  nmapmdnsclient:
    image: docker.io/instrumentisto/nmap:7.94
    networks:
      - opi
    command: --script=dns-service-discovery -p 5353 avahi

  client:
    image: docker.io/modularitycontainers/dhcp-client:latest
    cap_add:
      - CAP_NET_RAW
    volumes:
      - dhcp-leases-folder:/var/lib/dhclient/
      - ./dhcp/dhclient.conf:/etc/dhcp/dhclient.conf
    networks:
      - opi
    command: dhclient -d -v

  agent3: &agent
    image: ghcr.io/opiproject/opi-sztp-client:main
    build:
      context: sztp-agent
    depends_on:
      bootstrap:
        condition: service_healthy
      redirecter:
        condition: service_healthy
      setup-cert:
        condition: service_completed_successfully
    volumes:
      - client-certs:/certs
      - dhcp-leases-folder:/var/lib/dhclient/
      - /etc/os-release:/etc/os-release
      - /etc/ssh:/etc/ssh
    networks:
      - opi
    command: ['/opi-sztp-agent', 'daemon',
              '--dhcp-lease-file', '/var/lib/dhclient/dhclient.leases',
              '--bootstrap-trust-anchor-cert', '/certs/opi.pem',
              '--device-end-entity-cert', '/certs/third_my_cert.pem',
              '--device-private-key', '/certs/third_private_key.pem',
              '--serial-number', 'third-serial-number']

  agent2:
    <<: *agent
    command: ['/opi-sztp-agent', 'daemon',
              '--dhcp-lease-file', '/var/lib/dhclient/dhclient.leases',
              '--bootstrap-trust-anchor-cert', '/certs/opi.pem',
              '--device-end-entity-cert', '/certs/second_my_cert.pem',
              '--device-private-key', '/certs/second_private_key.pem',
              '--serial-number', 'second-serial-number']

  agent1:
    <<: *agent
    command: ['/opi-sztp-agent', 'daemon',
              '--dhcp-lease-file', '/var/lib/dhclient/dhclient.leases',
              '--bootstrap-trust-anchor-cert', '/certs/opi.pem',
              '--device-end-entity-cert', '/certs/first_my_cert.pem',
              '--device-private-key', '/certs/first_private_key.pem',
              '--serial-number', 'first-serial-number']

  agent4:
    <<: *agent
    command: ['/opi-sztp-agent', 'daemon',
              '--bootstrap-url', 'https://redirecter:8080/restconf/operations/ietf-sztp-bootstrap-server:get-bootstrapping-data',
              '--bootstrap-trust-anchor-cert', '/certs/opi.pem',
              '--device-end-entity-cert', '/certs/first_my_cert.pem',
              '--device-private-key', '/certs/first_private_key.pem',
              '--serial-number', 'first-serial-number']

  agent5:
    <<: *agent
    command: ['/opi-sztp-agent', 'run',
              '--dhcp-lease-file', '/var/lib/dhclient/dhclient.leases',
              '--bootstrap-trust-anchor-cert', '/certs/opi.pem',
              '--device-end-entity-cert', '/certs/first_my_cert.pem',
              '--device-private-key', '/certs/first_private_key.pem',
              '--serial-number', 'first-serial-number']

  agent6:
    <<: *agent
    volumes:
      - /var/run/dbus:/var/run/dbus
      - client-certs:/certs
      - /etc/os-release:/etc/os-release
      - /etc/ssh:/etc/ssh
    privileged: true
    command: ['/opi-sztp-agent', 'run',
              '--bootstrap-trust-anchor-cert', '/certs/opi.pem',
              '--device-end-entity-cert', '/certs/first_my_cert.pem',
              '--device-private-key', '/certs/first_private_key.pem',
              '--serial-number', 'first-serial-number']

volumes:
  client-certs:
  dhcp-leases-folder:
