FROM docker.io/library/python:3.10.7-slim

RUN apt update && apt install -y libyang-tools libxml2-utils make curl && rm -rf /var/lib/apt/lists/*

# certificates
RUN curl -kL https://watsen.net/support/sztpd-simulator-0.0.11.tgz | tar -zxvf - -C /tmp/
WORKDIR /tmp/sztpd-simulator/pki
RUN sed -i 's/localhost/bootstrap/g' sztpd1/sbi/end-entity/openssl.cnf
RUN make pki

# create trust chain
RUN cat sztpd1/sbi/root-ca/my_cert.pem sztpd1/sbi/intermediate1/my_cert.pem > /opi.pem

CMD ['/bin/sh', '-c', 'sleep infinity']
